language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
before_script:
  - ./code-check.sh
script:
  - python setup.py test
sudo: false
install:
  - pip install pep8
  - pip install flake8
  - pip install pep8-naming
