name: Python tests

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["2.7.18", "3.6.15", "3.7.15", "3.8.14", "3.9.15", "3.10.8", "3.11.0"]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pep8 flake8 pep8-naming
    - name: Test
      run: python setup.py test
